chore: use `11.x` range

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -33,6 +33,12 @@ jobs:
         with:
           node-version: ${{ matrix.node }}
 
+      - name: Check version
+        run: |
+          if [[ $(node -p "require('./packages/server/package.json').version.startsWith('10.')") != true ]]; then
+            echo "Error: The version in packages/server/package.json must start with '10.'"
+            exit 1
+          fi
       - name: Get pnpm store directory
         id: pnpm-cache
         run: |
@@ -49,9 +55,8 @@ jobs:
       - name: Install deps (with cache)
         run: pnpm --filter "@trpc/*" --filter root install
 
-      - run: pnpm build
-
       - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
         env:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-      - run: pnpm publish-canary --yes
+
+      - run: pnpm lerna publish --force-publish --canary major --preid next --dist-tag next --yes
